### ISSUE TITLE
set_positions service: service not available if the server is executed before the client

### ISSUE THREAD

**Issue by cosmac** [TechmanRobotInc/tmr_ros2#16]
Hey guys,

I recently installed the tmr_ros2 drivers and experimented with the available demos. All good so far, except that the "set_position" demo does not behave as I would expect. Here is the summary:
-  **Scenario#1 (Successful)**
Step#1: Run demo (set_positions node)
`$ ros2 run demo demo_set_positions`
Step#2: Next, run the TM driver
`$ ros2 run tm_driver tm_driver ip:=192.168.1.92`
In this case, as soon as the drivers are online, the request to move the joints is received and executed. The demo script finishes successful:
```
$ ros2 run demo demo_set_positions 
[INFO] [1638581348.011573916] [rclcpp]: service not available, waiting again...
...........
[INFO] [1638581355.014004046] [rclcpp]: service not available, waiting again...
[INFO] [1638581355.466903933] [rclcpp]: OK
```

- **Scenario#2 (service not available)**
Step#1: Run TM driver
`$ ros2 run tm_driver tm_driver ip:=192.168.1.92`
Step#2: Next, run demo
`$ ros2 run demo demo_set_positions`
In this case, the demo script never finds the service available and gets stuck in the loop that waits for the service:
`while (!client->wait_for_service(1s))`
From terminal I check that the service exists:
```
$ ros2 service list -t
/ask_item [tm_msgs/srv/AskItem]
/ask_sta [tm_msgs/srv/AskSta]
/connect_tmsct [tm_msgs/srv/ConnectTM]
/connect_tmsvr [tm_msgs/srv/ConnectTM]
/send_script [tm_msgs/srv/SendScript]
/set_event [tm_msgs/srv/SetEvent]
/set_io [tm_msgs/srv/SetIO]
/set_positions [tm_msgs/srv/SetPositions]
/tm_sct/describe_parameters [rcl_interfaces/srv/DescribeParameters]
/tm_sct/get_parameter_types [rcl_interfaces/srv/GetParameterTypes]
/tm_sct/get_parameters [rcl_interfaces/srv/GetParameters]
/tm_sct/list_parameters [rcl_interfaces/srv/ListParameters]
/tm_sct/set_parameters [rcl_interfaces/srv/SetParameters]
/tm_sct/set_parameters_atomically [rcl_interfaces/srv/SetParametersAtomically]
/tm_svr/describe_parameters [rcl_interfaces/srv/DescribeParameters]
/tm_svr/get_parameter_types [rcl_interfaces/srv/GetParameterTypes]
/tm_svr/get_parameters [rcl_interfaces/srv/GetParameters]
/tm_svr/list_parameters [rcl_interfaces/srv/ListParameters]
/tm_svr/set_parameters [rcl_interfaces/srv/SetParameters]
/tm_svr/set_parameters_atomically [rcl_interfaces/srv/SetParametersAtomically]
/write_item [tm_msgs/srv/WriteItem]
```
My expectation will be that the tm_driver can be run once, before or after the client, while multiple joint positions could be set by running the set_positions demo multiple times. Am I missing something here? 

**Note**: I'm running ROS2 Foxy with the [latest](https://github.com/TechmanRobotInc/tmr_ros2/tree/3ab4462cc637e0a58b629c2b6bcbd9b3780ab136) tmr_ros2 drivers (at this time)

Thanks!

**Comment by jean-fernandez-imt** [comment]
Hello Mr. Claudiu,

This is a very helpful post! I am also running into the very same issue. I am going to try following your successful scenario procedure first thing on Monday. 

I also wanted to add that this problem does not seem to appear on the ` tmr_driver`, since I had no issues when running the `tmr_moveit_cpp_demo`, that uses that driver. Without launching any driver previously. I just ran the following code:

```
ros2 launch tmr_moveit_cpp_demo run_moveit_cpp.launch.py robot_ip:=<robot_ip_address> 
```

This will also take care of launching the `tmr_driver`, that seems to have extra functionalities compared to `tm_driver`. (#6)

Have a good day!

**Comment by TechmanRobotIncOwner** [comment]
This issue is default DDS of new version Foxy is a little bit different from previous version.
So we recommend user other DDS, before we fixed this new issue.

Please refer to this below, use cyclone DDS.

"export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
 
If you have further question please let me know.
